### ISSUE TITLE
EQSANS: Complete task list

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#142]
This is the complete list of task to get a first cut of the EQSANS reduction backend.

*An item is checked once the code is complete and merged, and after a proper issue involving validation by instrument scientists has been created.*

## Prepare data
* [x] Load events and correct TOF (issue #66, integration issue #97)
* [x] Set instrument geometry (issue #66, integration issue #97)
* [x] Dark current correction (issue #100, integration issue #108)
* [x] Divide by flux (issue #105, integration issue #112)
* [x] Read and apply mask (issue #111, integration issue #117)
* [x] Initial uncertainty estimation (issue #113)
* [x] solid angle correction (issue #61, integration issue #94)
* [x] Apply sensitivity correction (#109, integration issue #125)
* [x] Normalize to time or monitor (issue #110)
* [x] Find beam center (issue #52, integration issue #95)

## Transmission correction
* [x] Compute and apply transmission (issue #55)

## Background subtraction and preparation of final data set
This should re-use all the previous tasks. All one needs is to check that the normalization is correct and that the binning matches the data.
* [x] Prepare, rebin and subtract background (issue #128)
* [ ] Final normalization after subtraction (absolute scale, and divide by sample size as needed).

## I(q) and I(qx, qy)
* [x] Perform I(qx, qy) calculation, including q resolution (issue #81)
* [x] Perform I(q) calculation, including q resolution (issue #82)

## Save output
* [x] Save I(q) in txt, and cansas format (issue #49)
* [ ] Save I(qx, qy)
* [ ] Save log file (issue #50)

## Extras
* [ ] Patch sensitivity (issue #153)

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/96).
