### ISSUE TITLE
First release: Complete Task List

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#185]
# Tasks

| Task | Issue | Assignee | Merged |
| ---- | ----- | -------- | -------|
|Source directory structure | #219  | @pf9 | Y |
| LICENSE file | #220 | @jbq | Y |
| CONTRIBUTING file | #221 | @m2d | Y  |
| File header | #222 | @jbq |  |
| README file | #223 | @pf9 | Y |
| Generate a conda package | #224 | @lj7  | Y |
| Internal API documentation | #225 | @pf9 |  |
| Momentum transfer performance | #226 | @wzz  | Y |
| A Merge Request template including the discussed software best practices | #227 | @pf9 | Y |
| Copyright Form | #233 | @bkj  | |

## Code Review
- [ ] Missing single-items
  + [ ] LICENSE file
    - [ ] GPL version 3 because we're using Mantid
  + [x] CONTRIBUTING file
  + [ ] standard header for source files. Should contain the authors list, a notice of copyright
- [ ] [Readme](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/blob/next/README.md) contents (different structure than Shaman's [Readme](https://code.ornl.gov/sns-hfir-scse/sans/sans-ui/blob/next/README.md))
  + [x] One-liner descriptive title
  + [x] abstract
  + [x] documentation (how to build locally, but no online docs)
  + [x] set-up for the developer
  + [x] running the tests
  + [x] Introduce better the contributing file
- [ ] Code quality
  + [x] functions exposed to the API have same name for all instruments
  + [ ] function arguments (like `input_workspace`) consistent
- [ ] Usability issues
  + [ ] command-line executable
- [ ] Style issues
  + [ ] Numpy-style docstrings
- [x] Documentation
  + [x] Docstrings build without warning in sphinx
  + [x] ability to build docus locally
  + [x] online documentation is available
- [ ] Hosted in:
  + [x] Gitlab
  + [ ] Github

## Copyright Submission
 
> (From Matt Garrett)  
> To start, you would want to go to https://ornl.service-now.com/ttc.  This is the portal for entering an open source copyright.  There are instructions listed on this site for entering in the information into our system for processing open source copyrights.
>
> I’ll look over the submission to ensure all the information entered makes sense and that there is a public link to the software that is active (e.g. Github).  Classification and Export Control will review as well.  We will also need to give notice to the cognizant DOE or government program manager who funded the development of the code unless it was LDRD.  Then no approval is required.
>
> Once all the internal review steps are, we send the open source submission to OSTI.  Essentially, at that point it is considered “open-source” in the eyes of the DOE.

- [Open Source Copyright Submission Instructions](https://ornl.service-now.com/ttc?id=ttc_content&category=3&content=NAV33&action=1) ([PDF version](/uploads/3cfcab5167f39a2e5867ada314a5f10c/instructions.pdf))
- [Portal](https://ornl.service-now.com/ttc) to fill the form

### Descriptive Title
> Enter a unique descriptive title for your code (up to 500 characters)

### Technical Problem
> Describe the technical problem your software addresses. Describe why the problem is important from a technical perspective.

### Technical Solution
> Describe the technical solution your software provides. Describe what the code does from a user’s perspective.

### Code’s Functionality
>  Describe how your software functions to provide the solution

### Advantages/Benefits
> Describe the features that make your software superior to existing technologies. Specifically identify competing state-of-the-art technologies and the advantages/benefits your software provides.

## Host in DOE CODE
?

# Minutes for SANS backend code review  
> copy license out of mantid - license can’t be the same as shaman  
> have notice of copyright at top of license as well as in its own file  
> Comments on README.md  
>      - Fix SHAMAN URL  
>      - Near information about using jupyter need a comment about "must have an xcams account" or something about user information at ORNL  
>      - Divide usage into two sections - one for xcams users and one for everyone else  
>      - Joe: add (small) table of contents  
>      - README should be an rst file for python compliance  
>      - Number 2 under docker - why is the script not in the repo?  
>        Pete: we need to rename the script anyway  
>        Pete: The README should point to the script in the script directory  
>        Jay: have some comment like "run the backend with the following commands". "assuming your user account is in the docker group, you can run the following command"  
>      - update the documentation build command  
>      - Greg: scripts files in scripts directory should include license statements in headers, as well as comments for what the script is for  
>      - change build scripts to run through setup.py   
>      - theme for python scripts on web documentation?  
>      - Robert: at no point do we say what exactly DRT-SANS is. Say this at some point in the beginning of the README  
>      - Wenduo: development instructions work  
>      - Do we do a conda install before release? Jay - nice to have a conda package, should make it  
>      - More explanatory text under license, contributing, and next branch sections  
>        Jay - move next branch information into contributing  
>      - short abstract at beginning of README to describe what the code does  
> - Hosted in gitlab or github? Put it on github, repo has to be public. We could put on the public repo if we do it close to when we submit the paperwork.  
> - have an automated thing to check the parsing of all the docstrings  
> - at the API documentation page, put the private stuff at the bottom? Change "API" to "Public API documentation" and at the bottom put "internal API documentation"  
> - try to get all of the issues that Jose discussed finished before release (or as many as possible)
> What to have done before merging magic branch into next?  
>      - fix readme  
>      - fix license  
>      - put the rest in as issues  
> - Change from ORNL.SANS to DRTSANS as the top level package name  
> - Matt: Get rid of some of the packaging levels?  
> - Some discussion about renaming files and condensing code if e.g. momentum_transfer functions have a lot of related code  
>   Shouldn't delay releasing code, but there is perhaps some condensing and better OO practices that could be implemented  
> - Pete: Priorities - fix momentum transfer, fix table workspace, then get rid of extract_spectrum  
>   re-examine performance once momentum transfer is fixed and table workspace isn't central  
> - all internal functions should have an underbar, as is python standard  
> - need more comments in meat of code - explain intent of code in comments  
>   for example, more clearly named variables (or leave the variables the same but give them better documentation)  
> - Pete: standardization of variable names? for everything  
>   e.g. is L2 the sample to the center of the detector or pixel? Make the documentation explicit and consistent and the variable consistent throughout  
>   better to be verbose in variable names. Should probably get rid of L2 completely since it means many different things to different groups  
>   document document document  
>   wl - wavelength  
>   s2p - sample_det_cent  
>   l1, l2, r1, r2, dwl...  
>   see e.g. solid_angle_correction.py for properly documented/named code  
> - document exception throwing, and create a standard for how errors/exceptions are handled  
> - backend needs to start signing off on commits to adhere to the CLA  
> - add authors to source code

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/139).
