### ISSUE TITLE
Refactor modules, classes and methods to calculate Q, Q resolution and I(Q)

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#260]
This is a master issue to refactor the modules, classes and methods to calculate momentum transfer in 2D with resolution and binning I(Q) in 1D and 2D.  

**Goal**
1. Removing TableWorkspace as the major data structure to hold q, dq, I(q) and dI(q)
1. Improving the efficiency in Q calculation and I(Q) binning
1. Renaming the modules, classes and methods to make them consistent with their functions.

**Tasks (in chronological order)**
1. [x] Rename momentum_transfer.py to iq.py (https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/merge_requests/210)
1. [x] Put all the momentum and momentum resolution calculation to momentum_transfer.py (https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/merge_requests/212)
1. [x] Refactor methods prepare_momentum_transfer (https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/merge_requests/213)
1. [x] Unit tests for HFIR q resolution (#) and EQSANS q resolution (#)
1. [x] Separate class MomentumTransfer to a series of static methods to binning I(Q) in 1D and 2D.

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/214).
