### ISSUE TITLE
Overwrite meta-data

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#427]
The following list of meta-data need to be parameters of `prepare_data`. Some already are, then please just confirm and make sure the units are correct.

- [x] Wavelength (overwrite log GP/BIO)
- [x] Wavelength spread (overwrite log GP/BIO)
- [ ] Sample-to-detector distance  (moved to #399)
- [ ] Source-to-sample distance  (moved to #399)
- [x] Sample aperture size (overwrite log)
- [x] Sample thickness
- [x] Source aperture size (overwrite log)
- [x] Pixel size X  (moved to #400)
- [x] Pixel size Y  (moved to #400)

https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/blob/next/drtsans/geometry.py#L377
https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/blob/next/drtsans/geometry.py#L427
