### ISSUE TITLE
HFIR-SANS: set sample and detector positions from meta data

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#481]
Implement the workflow, from JSON input to log file output, to apply
setting instrument sample and position position from meta data (including overwriting),
for Bio-SANS and GP-SANS.

**Tasks**

 - [x] 1. Determine the acceptance tests for BIO-SANS
 - [ ] 2. Determine the acceptance tests for GP-SANS
 - [x] 3. Implement back-end methods
 - [ ] 4. Modify BIO-SANS reduction script  --  **In Progress**
 - [ ] 5. Acceptance demo for BIO-SANS team
 - [ ] 6. Modify GP-SANS reduction script
 - [ ] 7. Acceptance demo for GP-SANS team

The branch won't be merged into next until all the above 7 tasks are completed.

From Volker
```
Drt-sans load calls mantid load
Sample [0,0,0], detector1 [0,0,sample_detector_distance]
Drt-sans load shall…
                Move instrument_component sample to [0,0,0.071- SampleToSi/1000]
Move instrument_component detector1 relative [0,0,0.071- SampleToSi/1000]
If drt-sans is provided with overwrite SampleToSi, then shall
Move instrument_component sample to [0,0,0.071- SampleToSi_overwrite/1000] 
[[Yes, this means redo the above operation first step, but not the second, this time using the new, overwritten value]]
If drt-sans is provided with overwrite sample_detector_distance, then shall
                Move instrument_component detector1 relative [0,0,sample_detector_distance_overwite - sample_detector_distance_nexus] 
 
This will work for Bio-SANS [checked with Venky, we walked through a specific example, see handwritten notes below];
it will work also for GP-SANS [checked with Ken and Lisa; however for GP-SANS please replace the [reference position] value ‘0.071’ with ‘0’;
```

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/435).
