### ISSUE TITLE
Converting OLD XML to NEW NeXus Format to use DRTSANS reduction

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#672]
Detectors:

We need to convert the data into Detector IDS... Keeping in mind that the front row of each 8pack goes from bank 1 to 24 and the back row goes from 25 to 48.

MetaData:

The meta data with motors needs a mapping into the new NeXus motors.
The interactive part would be the non-motor metadata parameters which would be populated by a mixture of XML metadata and user input.

FileName:

One aspect of sorting is the naming of the old XML that contained scan# and image#, now we have only a run#. OnCat does have all these files, but we may need to suppress the search or modify the way the search is done to locate the files during load.

Example:

OLD XML Raw Data -- [BioSANS_exp318_scan0007_0001.xml](/uploads/14495d7b57ccfef90887e2267ef8369d/BioSANS_exp318_scan0007_0001.xml)

Current NeXus -- Will be loaded later.

Suggested syntax to call the function-
`ConvertOLDXMLtoEventNeXus(input_XML_FileName,output_NeXus_FileName,metadata=None)`, where metadata is a dict{}.

**Sub issues**

 - [x] General libraries #628
 - [ ] Convert single GPSANS file #634
   - reopned in iteration 11: unexpected GPSANS file name
 - [ ] Prepare GPSANS pixel calibration and sensitivity file #638
 - [ ] GPSANS reduction workflow #645.
 - [ ] Convert single BioSANS file #646.
 - [ ] Prepare BISANS pixel calibration and sensitivity file #647
 - [ ] BioSANS reduction workflow #648

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/627).
