### ISSUE TITLE
Adapt GP-SANS legacy (xml) data to run through drtSANS jupyter notebooks

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#690]
As a GP-SANS Local Contact, I want to take legacy xml data that was taken before the major upgrade and run it through the new data reduction software so that new features that were implemented in drtSANS can be used on legacy data.
=======================================================================

| **Parent** | **Children** | **Related** | **Blocks** | **Depends On** |
|------------|--------------|-------------|------------|----------------|
|            |              |     #648        |            |                |

Acceptance Criteria:
--------------------
1. Convert legacy data (xml) to format for standard hdf5 file produced by EPICS/CSS using new convert script. The scientist will supply legacy xml file.
2. Run the new pixel calibration script that has been identified to be run on the newly converted legacy data from step 1.
3. Run the new sensitivity script that has been identified to be run on the newly converted legacy data to create a sensitivity file to be used in the gpsans_reduciton_multi_config.ipynb.
4. Run above notebook using porasil data listed below to compare to previously reduced data.

Description, Additional Detail, Context:
---------------------------------------
For format of hdf5 file....

Data to be used in acceptance criteria

Path to data:

/HFIR/CG2/IPTS-828/exp280/Datafiles

Bar Scan data: exp280   Scan005_001 - 0111

Sensitivity(10/29-11/22):

|**data** |**scatt center**| **trans center** | **scatt 200 off** | **trans 200 off** | **scatt 400 off**| **trans 400 off**|
|------------|--------------|-------------|------------|----------------|-----------|--------|
|   Exp280   |   Scan038    |    Scan037  |    Scan040  |    Scan039      | Scan042    | Scan041|

|**sample** |**19m12A scatt+trans** | **8m4.75 scatt** | **8m4.75 trans** | **2m4.75A scatt** | **2m4.75 center**|
|------------|--------------|-------------|------------|----------------|-----------|
|  Porasil B |   Scan023    |    Scan031  |    Scan027  |    Scan035      | Scan020    |
|  MT Cell |  Scan022   |  scan030   |  Scan026   | Scan034   |   |
|  MT air  |  Scan024   | Scan032| Scan028|Scan036|   |
|  block beam|Scan010|   Scan008 |    |   Scan009|   |

Suggested tasks:

- [ ] Use existing conversion script to convert xml data to nexus.
- [ ] Change pixel mapping script to handle converted data
- [ ] change sensitivity creation script to handle converted data
- [ ] Run converted standard data through jupyter notebook to verify that new data can run
- [ ] Compare output from drtSANS to output from legacy code for verification.

Implemented By Task(s): 
-----------------------
- [ ] Task: Convert SPICE to event Nexus file <https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/659>
- [ ] Task: Perform pixel calibration from bar scan data <https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/660>
- [ ] Task: Prepare sensitivities <https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/662>
- [ ] Task: Solve build server issue <https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/668> This is blocking
- [ ] Task: Reduce sample data (single data single configuration) <https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/663>
- [ ] Task: Refactor algorithms to load and compare reduced data, which have duplicated copies in multiple integration tests.
- [ ] Task: Regenerate integration test data and refactor integration test with template <https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/682>

Other:
-----------
Legacy ID:

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/645).
