### ISSUE TITLE
Adapt Bio-SANS legacy (xml) data to run through drtSANS jupyter notebooks

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#693]
As a Bio-SANS local contact, I want to take legacy xml data that was taken before the major upgrade and run it through the new data reduction software so that new features that were implemented in drtSANS can be used on legacy data.
=======================================================================

| **Parent** | **Children** |  **Related** | **Blocks** | **Depends On** |
|------------|--------------|--------------|------------|----------------|
|            |              |  #645        |            |   #646, #647   |

Acceptance Criteria:
--------------------
1. Use notebook- [RC488_IPTS24666_VolkerTemplate.py](/uploads/677fce379935722e4791693500cdecb9/RC488_IPTS24666_VolkerTemplate.py)

2. Reduce data of the following run_numbers-

Sample - /HFIR/CG3/IPTS-17240/exp318/Datafiles/BioSANS_exp318_scan0220_0001.xml (Scattering/Transmission)

Empty Beam - /HFIR/CG3/IPTS-17240/exp318/Datafiles/BioSANS_exp318_scan0217_0001.xml (For Transmission)

Beam Center - /HFIR/CG3/IPTS-17240/exp318/Datafiles/BioSANS_exp318_scan0217_0001.xml (Transmission Measurement)

Dark - /HFIR/CG3/IPTS-17240/exp318/Datafiles/BioSANS_exp318_scan0044_0001.xml (for both main and wing detectors)

*** In this case, we have no background subtraction.

Description, Additional Detail, Context:
---------------------------------------

- Check that the NXS file generated from XML file has all the necessary metadata variables for the notebook to reduce data.
- Use notebook that is currently being used for reducing NXS raw data.
- Change notebook to match the files provided - Sample, Empty Beam, Beam Center, Dark, Sensitivities. 

Implemented By Task(s): 
-----------------------
- [x] https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/673 Implement CG3 SPICE-converted event NeXus locator with functions to check meta data
- [x] https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/675 Identify the hard coded directories and files in Bio-SANS reduction
- [x] https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/674 Change notebook to match the files provided - Sample, Empty Beam, Beam Center, Dark, Sensitivities.

Other:
-----------
Legacy ID:

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/648).
