### ISSUE TITLE
List of Algorithms (update here!)

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#93]
Let's keep this update with the algorithms we can trash

```shell

# Can be removed because they set/launch the workflow
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSReduction.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/HFIRSANSReduction.py
* [ ]  Framework/WorkflowAlgorithms/src/SetupEQSANSReduction.cpp
* [ ]  Framework/WorkflowAlgorithms/src/SetupHFIRReduction.cpp


# Can be safely removed (because they have been replaced):
* [x]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSMask.py
* [x]  Framework/WorkflowAlgorithms/src/EQSANSDarkCurrentSubtraction.cpp
* [x]  Framework/WorkflowAlgorithms/src/SANSBeamFinder.cpp
* [x]  Framework/WorkflowAlgorithms/src/HFIRSANSNormalise.cpp


# Ricardo Working
* [ ]  Framework/WorkflowAlgorithms/src/SANSSolidAngleCorrection.cpp
* [ ]  Framework/WorkflowAlgorithms/src/EQSANSLoad.cpp
* [ ]  Framework/WorkflowAlgorithms/src/HFIRLoad.cpp
* [ ]  Framework/DataHandling/src/LoadSpice2D.cpp

# Jose working
* [ ]  Framework/WorkflowAlgorithms/src/EQSANSTofStructure.cpp
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSNormalise.py
* [ ]  Framework/WorkflowAlgorithms/src/EQSANSMonitorTOF.cpp
* [ ]  Framework/WorkflowAlgorithms/src/SANSBeamFluxCorrection.cpp

# SANS Algorithms that won't be changed (for now) and can be used in the future:
- FindCenterOfMassPosition2

# New Algorithms
- SANSMaskDTP

# Moved from Workflow to Algorithms
- SANSSolidAngleCorrection

# TODO:

* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSAzimuthalAverage1D.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSDirectBeamTransmission.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/NormaliseByThickness.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReactorSANSResolution.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSAbsoluteScale.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSAzimuthalAverage1D.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSBeamSpreaderTransmission.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSDirectBeamTransmission.py
* [ ]  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransmissionUtils.py

* [ ]  Framework/WorkflowAlgorithms/src/EQSANSQ2D.cpp
* [ ]  Framework/WorkflowAlgorithms/src/HFIRDarkCurrentSubtraction.cpp
* [ ]  Framework/WorkflowAlgorithms/src/SANSSensitivityCorrection.cpp


```

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/7).
