### ISSUE TITLE
Top-level API for SANS prepare data

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#97]
**Epic-level issue to be split into story-level issues**

Major feature branch: https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/commits/eqsans_prepare_data

Write a high-level API to load SANS data. This should abstract out the specific Mantid loaders.
The result should be a simple API with atomic functions that have Mantid workspaces as input/output.

See section 2 and 3 of the [requirements](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/blob/master/documents/Master_document_022219.pdf) document.

The following is a complete list, which should be sub-tasks (the code running each of those calculations will in many cases be the same across instruments):

**EQSANS** (Related major feature branch: `eqsans_prepare_data`)
- [x] Load events and correct TOF (issue #66)
- [x] Set instrument geometry (issue #66)
- [ ] Dark current correction
- [ ] Divide by flux
- [ ] Read and apply mask
- [ ] Initial uncertainty estimation
- [ ] solid angle correction (issue #61)
- [ ] Apply sensitivity correction
- [ ] Normalize to time, monitor, or proton charge
- [x] Find beam center (issue #52)

**BIOSANS**
- [ ] Load data
- [ ] Read and apply mask
- [ ] Initial uncertainty estimation
- [ ] Set instrument geometry
- [ ] Dark current correction
- [ ] solid angle correction (issue #61)
- [ ] Apply sensitivity correction
- [ ] Normalize to time, monitor, or proton charge
- [ ] Find beam center

**GPSANS**
- [ ] Load data
- [ ] Read and apply mask
- [ ] Initial uncertainty estimation
- [ ] Set instrument geometry
- [ ] Dark current correction
- [ ] solid angle correction (issue #61)
- [ ] Apply sensitivity correction
- [ ] Normalize to time, monitor, or proton charge
- [ ] Find beam center

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/51).
